// Generated by CodiumAI

import { dbConnect } from "@/db";
import { Home } from "lucide-react";
import { render } from "react-dom";

describe('Home', () => {

    // Tests that the Home component renders without errors
    it('should render without errors', () => {
        render(<Home />);
    });


    // Tests that the Home component renders without crashing
    it('should render the Home component without crashing', () => {
        render(<Home />);
    });


    // Tests that all users are displayed from the database
    it('should display all users from the database', async () => {
        const allUsers = [{ fullName: 'John Doe', phone: '1234567890' }, { fullName: 'Jane Doe', phone: '0987654321' }];
        dbConnect.select.mockResolvedValueOnce(allUsers);
        render(<Home />);
        await waitFor(() => expect(screen.getByText(JSON.stringify(allUsers, null, 2))).toBeInTheDocument());
    });


});
